replicaCount: 3

configGenerator:
  podAnnotations: { }

  podSecurityContext: { }
  # fsGroup: 2000

  nodeSelector: { }

  tolerations: [ ]

  affinity: { }

  image:
    repository: ghcr.io/hfuss/quorum-config-generator
    pullPolicy: Always
    tag: latest

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

bootnode:
  storage: 128Mi
  podAnnotations: { }

  podSecurityContext: { }
  # fsGroup: 2000

  nodeSelector: { }

  tolerations: [ ]

  affinity: { }

  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
     limits:
       cpu: 100m
       memory: 32Mi
     requests:
       cpu: 10m
       memory: 32Mi

  image:
    repository: ghcr.io/hfuss/quorum
    pullPolicy: Always
    tag: latest
  securityContext: { }
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  serviceAccount:
    create: true
    annotations: { }

  service:
    type: ClusterIP
    port: 30301


quorum:
  storage: 256Mi
  image:
    repository: ghcr.io/hfuss/quorum
    pullPolicy: Always
    tag: latest

  podAnnotations: {}

  podSecurityContext: {}
  # fsGroup: 2000

  nodeSelector: {}

  tolerations: []

  affinity: {}

  constellation:
    image:
      repository: ghcr.io/hfuss/constellation
      pullPolicy: Always
      tag: latest
    resources:
      limits:
        cpu: 500m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 64Mi
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
    securityContext: { }
      # capabilities:
      #   drop:
      #   - ALL
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000

  securityContext: { }
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  serviceAccount:
    create: true
    annotations: { }
    name: ""

  service:
    type: ClusterIP
    gethPort: 8545
    otherPort: 8546

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 256Mi
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

