apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quorum.fullname" . }}-runtime-scripts
  labels:
    {{ include "quorum.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "scripts/init-*").AsConfig | indent 2 }}
{{ (.Files.Glob "scripts/start-*").AsConfig | indent 2 }}
