apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quorum.fullname" . }}-config-scripts
  labels:
    {{ include "quorum.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: keep
data:
{{ (.Files.Glob "scripts/generate-config.sh").AsConfig | indent 2 }}
