apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quorum.fullname" . }}-test-scripts
  labels:
    {{ include "quorum.labels" . | nindent 4 }}
    app.kubernetes.io/component: testing
data:
{{ (.Files.Glob "scripts/test*.sh").AsConfig | indent 2 }}
{{ (.Files.Glob "scripts/*.js").AsConfig | indent 2 }}
