apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "quorum.fullname" . }}-config
  labels:
    {{- include "quorum.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.longhornStorageEnabled }}
  storageClassName: longhorn
  {{- end }}
  resources:
    requests:
      storage: 64Mi
