{{- if .Values.bootnode.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quorum.serviceAccountName" . }}-bootnode
  labels:
    {{- include "quorum.labels" . | nindent 4 }}
    app.kubernetes.io/component: bootnode
  {{- with .Values.bootnode.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
