apiVersion: v1
kind: Service
metadata:
  name: {{ include "quorum.fullname" . }}-bootnode
  labels:
    {{- include "quorum.labels" . | nindent 4 }}
    app.kubernetes.io/component: bootnode
spec:
  type: {{ .Values.bootnode.service.type }}
  ports:
    - port: {{ .Values.bootnode.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "quorum.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: bootnode
