apiVersion: v1
kind: Service
metadata:
  name: {{ include "quorum.fullname" . }}
  labels:
    {{- include "quorum.labels" . | nindent 4 }}
    app.kubernetes.io/component: quorum
spec:
  type: {{ .Values.quorum.service.type }}
  ports:
    - port: {{ .Values.quorum.service.gethPort }}
      targetPort: geth
      protocol: TCP
      name: geth
    - port: {{ .Values.quorum.service.otherPort }}
      targetPort: other
      protocol: TCP
      name: other
  selector:
    {{- include "quorum.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: quorum
