{{- if .Values.quorum.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quorum.serviceAccountName" . }}
  labels:
    {{- include "quorum.labels" . | nindent 4 }}
  {{- with .Values.quorum.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
